### ISSUE TITLE
Cannot build or setup project

### ISSUE THREAD

**Issue by ghost** [Gav06/Moonlight#1]
```Could not find net.minecraftforge:forgeBin:1.12.2-14.23.5.2847.```

```
Could not find net.minecraftforge:forgeBin:1.12.2-14.23.5.2847.
Searched in the following locations:
  - https://maven.minecraftforge.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://maven.minecraftforge.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - https://libraries.minecraft.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://libraries.minecraft.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - https://repo.spongepowered.org/repository/maven-public/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://repo.spongepowered.org/repository/maven-public/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - file:/C:/Users/berii/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - file:/C:/Users/berii/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - file:/C:/Users/berii/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.5.2847/stable/39/forgeBin-1.12.2-14.23.5.2847.jar
  - file:/C:/Users/berii/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.5.2847/stable/39/forgeBin.jar
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by ghost** [comment]
> `Could not find net.minecraftforge:forgeBin:1.12.2-14.23.5.2847.`
> 
> ```
> Could not find net.minecraftforge:forgeBin:1.12.2-14.23.5.2847.
> Searched in the following locations:
>   - https://maven.minecraftforge.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
>   - https://maven.minecraftforge.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
>   - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
>   - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
>   - https://libraries.minecraft.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
>   - https://libraries.minecraft.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
>   - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
>   - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
>   - https://repo.spongepowered.org/repository/maven-public/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
>   - https://repo.spongepowered.org/repository/maven-public/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
>   - file:/C:/Users/berii/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
>   - file:/C:/Users/berii/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
>   - file:/C:/Users/berii/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.5.2847/stable/39/forgeBin-1.12.2-14.23.5.2847.jar
>   - file:/C:/Users/berii/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.5.2847/stable/39/forgeBin.jar
> Required by:
>     project :
> 
> Possible solution:
>  - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
> ```

did you by any chance try to use the fucking possible solution

**Comment by Gav06** [comment]
run `gradlew setupDecompWorkspace --refresh-dependencies`

**Comment by ghost** [comment]
> run `gradlew setupDecompWorkspace --refresh-dependencies`

🚬

**Comment by AcaiBerii** [comment]
> > run `gradlew setupDecompWorkspace --refresh-dependencies`
> 
> 🚬

💊 also im using the default build.gradle ur issue :bruh:

**Comment by ghost** [comment]
> > > run `gradlew setupDecompWorkspace --refresh-dependencies`
> > 
> > 
> > 🚬
> 
> 💊 also im using the default build.gradle ur issue :bruh:

def not we never had these issues your just dumb

**Comment by ghost** [comment]
i forgot how to use the older versions of forgegradle because i usually just use ```gradlew build```
